name: Semantic release checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  conventional-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate commit messages
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
        if: github.event_name == 'pull_request'
